#!/usr/bin/env python3
"""Template configuration: ASSEMBLER_CONFIG, C() helper, and type mappings"""


def C(*a, **kw):
    return {
        "t": a[0],
        "v": a[1],
        "p": a[2],
        "i": a[3],
        "g": a[4],
        "c": a[5],
        "n": a[6],
        "x": kw.get("x", []),
        "y": kw.get("y", []),
        "cn": kw.get("cn", ""),
    }


ASSEMBLER_CONFIG = {
    # fields: (tmpl, ver, type_val, id, tags, conf, (ns,nl,ni), extra_fm, extra_bd)
    "concept": C(
        "concept_template.md",
        "v6.1",
        ("override_type", "concept"),
        "concept_id",
        ["概念"],
        0.95,
        (1, 1, 1),
        cn="定义可从原文逐字匹配，经人工复核",
        x=[
            "concept_type::定义",
            "concept_level::核心",
            "bloom_level::理解",
            "definition_source",
            "additional_explanations",
            "formula_references",
            "figure_references",
            "core_concept_map_source",
            "features::无",
            "structure::无",
            "prerequisites::无",
            "factors::无",
            "related_knowledge::无",
            "confusion_compare::无",
            "domain::无",
            "classification::无",
            "boundary::无",
            "application_scenarios::无",
            "value::无",
            "upstream_downstream::无",
            "evolution::无",
            "key_parameters::无",
            "common_misconceptions::无",
            "references::无",
            "related_knowledge_elements::无",
            "related_toc::无",
            "source::无",
            "term_definition::无",
            "core_concept_map::无",
            "core_concept_map_analysis::无",
            "mathematical_model::无",
            "tech_classification::无",
            "typical_systems::无",
            "related_concepts_relations::无",
            "engineering_practices::无",
            "confidence_note::精准释义逐字匹配出处原文",
        ],
        y=[
            "definition_sentence:definition",
            "term_english",
            "term_definition",
            "definition_source",
            "additional_explanations",
            "formula_references",
            "figure_references",
            "core_concept_map",
            "core_concept_map_source",
            "core_concept_map_analysis",
            "structure",
            "mathematical_model",
            "tech_classification",
            "application_scenarios",
            "typical_systems",
            "related_concepts_relations",
            "confusion_compare",
            "evolution",
            "engineering_practices",
            "common_misconceptions",
            "references",
            "related_knowledge_elements",
            "source",
            "concept_type",
            "concept_level",
            "bloom_level",
            "features",
            "prerequisites",
            "factors",
            "related_knowledge",
            "domain",
            "classification",
            "boundary",
            "value",
            "upstream_downstream",
            "key_parameters",
            "related_toc",
        ],
    ),
    "knowledge": C(
        "knowledge_template.md",
        "v5.0",
        ("_S", "knowledge"),
        "knowledge_id",
        ["知识点"],
        0.85,
        (1, 1, 1),
        cn="内容基于正文归纳，关键结论可溯源",
        x=[
            "knowledge_level::核心",
            "bloom_level::理解",
            "difficulty::中",
            "content_core",
            "content_significance::无",
            "content_difficulties::无",
            "prerequisites::无",
            "follow_ups::无",
            "examples::无",
            "referenced_concepts::无",
            "learning_objectives::无",
            "domain::无",
            "theoretical_basis::无",
            "key_details::无",
            "application_scenarios::无",
            "application_methods::无",
            "typical_examples::无",
            "common_exam_points::无",
            "exam_questions::无",
            "exam_point_analysis::无",
            "related_concepts::无",
            "related_knowledge_elements::无",
            "prerequisite_knowledge::无",
            "supported_skills_scenarios::无",
            "confusion_compare_table::无",
            "derivation_diagram::无",
            "derivation_analysis::无",
            "core_knowledge_elements_table::无",
            "knowledge_context_diagram::无",
            "diagram_analysis::无",
        ],
        y=[
            "content_core",
            "learning_objectives::无",
            "domain::无",
            "theoretical_basis::无",
            "key_details::无",
            "derivation_diagram::无",
            "derivation_analysis::无",
            "core_knowledge_elements_table::无",
            "application_scenarios::无",
            "application_methods::无",
            "typical_examples::无",
            "common_exam_points::无",
            "exam_questions::无",
            "exam_point_analysis::无",
            "related_concepts::无",
            "related_knowledge_elements::无",
            "prerequisite_knowledge::无",
            "supported_skills_scenarios::无",
            "confusion_compare_table::无",
            "knowledge_context_diagram::无",
            "diagram_analysis::无",
        ],
    ),
    "skill": C(
        "skill_template.md",
        "v5.0",
        ("_S", "skill"),
        "skill_id",
        ["技能点"],
        0.75,
        (1, 1, 1),
        cn="操作步骤来自原文或教材标准流程",
        x=[
            "skill_level::L1",
            "bloom_level::应用",
            "difficulty::中",
            "skill_description",
            "skill_steps::无",
            "standard_pass::无",
            "capability_standard::无",
            "key_techniques::无",
            "common_tools::无",
            "precautions::无",
            "related_concepts::无",
            "related_knowledge::无",
            "application_scenarios::无",
            "typical_cases::无",
            "confusion_compare_table::无",
            "operation_diagram::无",
            "operation_analysis::无",
            "knowledge_elements::无",
            "evolution",
            "references::无",
            "skill_objectives::通过本技能学习达到以下能力",
            "domain::（待指定）",
            "core_operation::无",
            "competency_standards::无",
            "operation_boundaries::无",
            "core_theoretical_support::无",
            "tool_support::无",
            "prerequisite_skills::无",
            "applicable_scenarios::无",
            "operation_flowchart::无",
            "operation_flow_analysis::无",
            "typical_practical_cases::无",
            "related_concepts_knowledge::无",
            "supported_scenarios::无",
            "extended_skills::无",
            "confusion_skill_compare::无",
            "knowledge_context_diagram::无",
            "diagram_analysis::无",
        ],
        y=[
            "skill_description",
            "skill_steps::无",
            "standard_pass::无",
            "capability_standard::无",
            "key_techniques::无",
            "common_tools::无",
            "precautions::无",
            "related_concepts::无",
            "related_knowledge::无",
            "application_scenarios::无",
            "typical_cases::无",
            "confusion_compare_table::无",
            "operation_diagram::无",
            "operation_analysis::无",
            "knowledge_elements::无",
            "evolution::无",
            "references::无",
            "skill_objectives::通过本技能学习达到以下能力",
            "domain::（待指定）",
            "core_operation::无",
            "competency_standards::无",
            "operation_boundaries::无",
            "core_theoretical_support::无",
            "tool_support::无",
            "prerequisite_skills::无",
            "applicable_scenarios::无",
            "operation_flowchart::无",
            "operation_flow_analysis::无",
            "typical_practical_cases::无",
            "related_concepts_knowledge::无",
            "supported_scenarios::无",
            "extended_skills::无",
            "confusion_skill_compare::无",
            "knowledge_context_diagram::无",
            "diagram_analysis::无",
        ],
    ),
    "scenario": C(
        "scenario_template.md",
        "v5.0",
        ("_S", "scenario"),
        "scenario_id",
        ["应用场景"],
        0.65,
        (1, 1, 1),
        cn="场景基于教材案例或实际工程经验构建",
        x=[
            "scenario_level::L1",
            "bloom_level::应用",
            "difficulty::中",
            "scenario_description",
            "typical_workflow::无",
            "workflow_diagram::无",
            "diagram_analysis::无",
            "context_diagram::无",
            "context_analysis::无",
            "boundary_conditions::无",
            "prerequisites::无",
            "key_techniques::无",
            "common_tools::无",
            "success_criteria::无",
            "common_pitfalls::无",
            "related_concepts::无",
            "related_knowledge::无",
            "related_skills::无",
            "references::无",
            "scenario_type::产品认证",
            "domain::（待指定）",
            "scene_elements::无",
            "constraints::无",
            "technical_environment::无",
            "core_knowledge_support::无",
            "core_skill_support::无",
            "confusion_scenario_compare::无",
            "evolution::无",
        ],
        y=[
            "scenario_description",
            "typical_workflow::无",
            "workflow_diagram::无",
            "diagram_analysis::无",
            "context_diagram::无",
            "context_analysis::无",
            "boundary_conditions::无",
            "prerequisites::无",
            "key_techniques::无",
            "common_tools::无",
            "success_criteria::无",
            "common_pitfalls::无",
            "related_concepts::无",
            "related_knowledge::无",
            "related_skills::无",
            "references::无",
            "scenario_type::产品认证",
            "domain::（待指定）",
            "scene_elements::无",
            "constraints::无",
            "technical_environment::无",
            "core_knowledge_support::无",
            "core_skill_support::无",
            "confusion_scenario_compare::无",
            "evolution::无",
            "scene_concept_support::无",
            "scene_ke_support::无",
            "workflow_analysis::无",
            "typical_application_cases::无",
            "related_scenes::无",
            "knowledge_context_diagram::无",
        ],
    ),
    "entity": C(
        "concept_template.md",
        "v6.1",
        ("_S", "entity"),
        "entity_id",
        ["实体"],
        0.85,
        (1, 0, 1),
        cn="事实信息可溯源",
        x=[
            "entity_type::设备",
            "category::无",
            "specifications::无",
            "features::无",
            "application_scenarios::无",
            "references::无",
        ],
        y=[
            "entity_type::设备",
            "category::无",
            "specifications::无",
            "features::无",
            "application_scenarios::无",
            "references::无",
            "description::无",
            "related_concepts::无",
        ],
    ),
    "knowledge-element": C(
        "concept_template.md",
        "v6.1",
        ("_S", "knowledge-element"),
        "ke_id",
        ["知识要素"],
        0.85,
        (1, 0, 1),
        cn="基于正文内容归纳生成",
        x=[
            "domain::无",
            "classification::无",
            "structure::无",
            "key_parameters::无",
            "features::无",
            "application_scenarios::无",
            "value::无",
            "upstream_downstream::无",
            "related_knowledge_elements::无",
            "references::无",
            "source::无",
        ],
        y=[
            "definition::无",
            "domain::无",
            "classification::无",
            "structure::无",
            "key_parameters::无",
            "features::无",
            "application_scenarios::无",
            "value::无",
            "upstream_downstream::无",
            "related_knowledge_elements::无",
            "references::无",
            "source::无",
        ],
    ),
    "exercise": C(
        "exercise_template.md",
        "v6.1",
        ("_S", "exercise"),
        "exercise_id",
        ["习题"],
        0.65,
        (1, 0, 1),
        cn="自动检测+解答wikilink",
        x=[
            "exercise_type::问答题",
            "difficulty::中",
            "source_file",
            "related_concepts",
            "related_knowledge_elements::无",
            "answer::无",
        ],
        y=[
            "exercise_type::问答题",
            "difficulty::中",
            "source_file::无",
            "related_concepts::无",
            "related_knowledge_elements::无",
            "related_answer::无",
        ],
    ),
    "solution": C(
        "eval_template.md",
        "v6.1",
        ("_S", "solution"),
        "solution_id",
        ["习题解答"],
        0.65,
        (1, 0, 1),
        cn="自动检测+解答wikilink",
        x=[
            "question::无",
            "exam_point_analysis::无",
            "difficulty_analysis::无",
            "problem_solving_flowchart::无",
            "problem_solving_analysis::无",
            "knowledge_closed_loop::无",
            "closed_loop_analysis::无",
            "references::无",
            "exercise_link::无",
            "exercise_name::无",
        ],
        y=[
            "question::无",
            "answer::无",
            "exam_point_analysis::无",
            "difficulty_analysis::无",
            "problem_solving_flowchart::无",
            "problem_solving_analysis::无",
            "knowledge_closed_loop::无",
            "closed_loop_analysis::无",
            "references::无",
            "exercise_link::无",
            "exercise_name::无",
        ],
    ),
    "index": C(
        "concept_index.md",
        "v3.0",
        ("override_type", "index"),
        "id",
        ["索引"],
        0.95,
        (1, 0, 0),
        cn="自动索引",
        x=[
            "total_count",
            "index_type",
        ],
        y=[
            "items_table",
        ],
    ),
    "book_overview": C(
        "book_overview.md",
        "v3.0",
        ("override_type", "book_overview"),
        "book_id",
        ["总揽"],
        0.95,
        (1, 0, 0),
        cn="自动总揽",
        x=[
            "book_name",
            "domain",
            "stats",
            "chain_connectivity",
            "graph_quality",
            "top_nodes",
            "mindmap_content",
            "chapter_distribution",
            "learning_path",
        ],
        y=[
            "book_name",
            "stats",
            "chain_connectivity",
            "node_connectivity",
            "graph_quality",
            "top_nodes",
            "mindmap_content",
            "chapter_distribution",
            "learning_path",
        ],
    ),
}

# ── NODE_CONFIG: 类型名 → ASSEMBLER_CONFIG 映射 ──
NODE_CONFIG = {
    "concept": ASSEMBLER_CONFIG["concept"],
    "knowledge": ASSEMBLER_CONFIG["knowledge"],
    "skill": ASSEMBLER_CONFIG["skill"],
    "scenario": ASSEMBLER_CONFIG["scenario"],
    "ke": ASSEMBLER_CONFIG["knowledge-element"],
    "entity": ASSEMBLER_CONFIG["entity"],
    "exercise": ASSEMBLER_CONFIG["exercise"],
    "solution": ASSEMBLER_CONFIG["solution"],
    "index": ASSEMBLER_CONFIG["index"],
    "book_overview": ASSEMBLER_CONFIG["book_overview"],
}

# Standard frontmatter fields
_STD_FM = [
    "template_version",
    "type",
    "type_tags",
    "name",
    "book_id",
    "book_name",
    "chapter_num",
    "id_field",
    "confidence",
    "confidence_note",
    "source_chapter",
    "source_page",
    "source_from",
    "reviewer",
    "review_date",
    "aliases",
    "tags",
]

# Standard body fields
_STD_BD = [
    "name",
    "id_field",
    "source_chapter",
    "source_page",
    "source_from",
    "book_id",
    "book_name",
    "chapter_num",
    "reviewer",
    "review_date",
]
